# Decision Trees
(Reon)

### Contents:
1. Data Analysis
2. Feature engineering
2. Tree Building/Training

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv('AAPL.csv') #Read the data in
df.Date = pd.to_datetime(df.Date, format='%d/%m/%Y') #Set the date column to datetime
df.set_index('Date', inplace=True) #Set the index to the date column
df = df.rename(columns = {'Adj Close':'Adj_Close'})
df.head(20) #Observe a few rows of data

FileNotFoundError: File b'AAPL.csv' does not exist

In [5]:
aapl = pd.read_csv("C:\\Users\\reonh\\Documents\\NUS\\1920 S1\\FINTECH\\AAPL (2).csv")

In [6]:
train = aapl[aapl["Date"]

,Date,Open,High,Low,Close,Adj Close,Volume
0,1/9/2015,110.150002,111.879997,107.360001,107.720001,100.533249,76845900
1,2/9/2015,110.230003,112.339996,109.129997,112.339996,104.845024,61888800
2,3/9/2015,112.489998,112.779999,110.040001,110.370003,103.006447,53233900
3,4/9/2015,108.970001,110.449997,108.510002,109.269997,101.979836,49996300
4,8/9/2015,111.750000,112.559998,110.320000,112.309998,104.817017,54843600
5,9/9/2015,113.760002,114.019997,109.769997,110.150002,102.801125,85010800
6,10/9/2015,110.269997,113.279999,109.900002,112.570000,105.059677,62892800
7,11/9/2015,111.790001,114.209999,111.760002,114.209999,106.590263,49915500
8,14/9/2015,116.580002,116.889999,114.860001,115.309998,107.616867,58363400
9,15/9/2015,115.930000,116.529999,114.419998,116.279999,108.522148,43341200
10,16/9/2015,116.250000,116.540001,115.440002,116.410004,108.643478,37173500
11,17/9/2015,115.660004,116.489998,113.720001,113.919998,106.319611,64112600
12,18/9/2015,112.209999,114.300003,111.870003,113.449997,105.880959,74285300
13,21/9/2015,113.669998,115.370003,113.660004,115.209999,107.523544,50222000
14,22/9/2015,113.379997,114.180000,112.519997,113.400002,105.834305,50346200
15,23/9/2015,113.629997,114.720001,113.300003,114.320000,106.692917,35756700
16,24/9/2015,113.250000,115.500000,112.370003,115.000000,107.327568,50219500
17,25/9/2015,116.440002,116.690002,114.019997,114.709999,107.056892,56151900
18,28/9/2015,113.849998,114.570000,112.440002,112.440002,104.938339,52109000
19,29/9/2015,112.830002,113.510002,107.860001,109.059998,101.783844,73365400
20,30/9/2015,110.169998,111.540001,108.730003,110.300003,102.941124,66473000
21,1/10/2015,109.070000,109.620003,107.309998,109.580002,102.269157,63929100
22,2/10/2015,108.010002,111.010002,107.550003,110.379997,103.015785,58019800
23,5/10/2015,109.879997,111.370003,109.070000,110.779999,103.389107,52064700
24,6/10/2015,110.629997,111.739998,109.769997,111.309998,103.883736,48196800
25,7/10/2015,111.739998,111.769997,109.410004,110.779999,103.389107,46765600
26,8/10/2015,110.190002,110.190002,108.209999,109.500000,102.194481,61979600
27,9/10/2015,110.000000,112.279999,109.489998,112.120003,104.639717,52766100
28,12/10/2015,112.730003,112.750000,111.440002,111.599998,104.154366,30467200
29,13/10/2015,110.820000,112.449997,110.680000,111.790001,104.331711,33049300
...,...,...,...,...,...,...,...
977,22/7/2019,203.649994,207.229996,203.610001,207.220001,206.435654,22277900
978,23/7/2019,208.460007,208.910004,207.289993,208.839996,208.049515,18355200
979,24/7/2019,207.669998,209.149994,207.169998,208.669998,207.880173,14991600
980,25/7/2019,208.889999,209.240005,206.729996,207.020004,206.236420,13909600
981,26/7/2019,207.479996,209.729996,207.139999,207.740005,206.953690,17618900
982,29/7/2019,208.460007,210.639999,208.440002,209.679993,208.886337,21673400
983,30/7/2019,208.759995,210.160004,207.309998,208.779999,207.989746,33935700
984,31/7/2019,216.419998,221.369995,211.300003,213.039993,212.233627,69281400
985,1/8/2019,213.899994,218.029999,206.740005,208.429993,207.641068,54017900
986,2/8/2019,205.529999,206.429993,201.630005,204.020004,203.247772,40862100
987,5/8/2019,197.990005,198.649994,192.580002,193.339996,192.608185,52393000
988,6/8/2019,196.309998,198.070007,194.039993,197.000000,196.254333,35824800
989,7/8/2019,195.410004,199.559998,193.820007,199.039993,198.286606,33364400
990,8/8/2019,200.199997,203.529999,199.389999,203.429993,202.659988,27009500
991,9/8/2019,201.300003,202.759995,199.289993,200.990005,200.990005,24619700
992,12/8/2019,199.619995,202.050003,199.149994,200.479996,200.479996,22474900
993,13/8/2019,201.020004,212.139999,200.479996,208.970001,208.970001,47218500
994,14/8/2019,203.160004,206.440002,202.589996,202.750000,202.750000,36547400
995,15/8/2019,203.460007,205.139999,199.669998,201.740005,201.740005,27227400
996,16/8/2019,204.279999,207.160004,203.839996,206.500000,206.500000,27620400
997,19/8/2019,210.619995,212.729996,210.029999,210.350006,210.350006,24413600
998,20/8/2019,210.880005,213.350006,210.320007,210.360001,210.360001,26884300
999,21/8/2019,212.990005,213.649994,211.600006,212.639999,212.639999,21535400
1000,22/8/2019,213.190002,214.440002,210.750000,212.460007,212.460007,22253700
1001,23/8/2019,209.429993,212.050003,201.000000,202.639999,202.639999,46818000
1002,26/8/2019,205.860001,207.190002,205.059998,206.490005,206.490005,26043600
1003,27/8/2019,207.860001,208.550003,203.529999,204.160004,204.160004,25873300
1004,28/8/2019,204.100006,205.720001,203.320007,205.529999,205.529999,15938800
1005,29/8/2019,208.500000,209.320007,206.660004,209.009995,209.009995,20990500
1006,30/8/2019,210.160004,210.449997,207.199997,208.740005,208.740005,21143400